format = """
[](#3B4252)\
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$nodejs\
$rust\
$golang\
$python\
$cmd_duration\
$line_break\
$character"""

[directory]
style = "cyan bold"
format = "[ $path ]($style)"
truncation_length = 3
# truncation_symbol = "…/"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
format = "[$branch]($style)"
style = "bright-red"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[golang]
format = "[ $version](bold cyan) "
disabled = true

[python]
format = "[$symbol$version](bold blue) "
disabled = true

[nodejs]
format = "[$symbol$version](bold green) "
disabled = false

[rust]
format = "[ $version](red bold) "
disabled = true

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"
